import Image from "next/image";
import { ArrowUpRight, BusFront, Footprints, MapPin } from "lucide-react";
const Tags=({items}:{items:string[]})=><div className="flex flex-wrap gap-2">{items.map(item=><span key={item} className="code-font rounded-full border border-black/15 px-3 py-1 text-[11px] uppercase tracking-wide">{item}</span>)}</div>;
export default function Projects(){return <section id="work" className="py-20 sm:py-28">
<div className="mb-12 border-b border-black/15 pb-6"><p className="section-kicker">Selected work · 2026</p><h2 className="heading-font mt-3 text-5xl sm:text-7xl">Built beyond the tutorial.</h2></div>
<article className="grid overflow-hidden border border-black/15 lg:grid-cols-2">
<div className="project-grid min-h-[460px] p-6 sm:p-10"><div className="flex h-full flex-col rounded-[28px] border border-black/15 bg-[#f7f3ea] p-5 shadow-[0_20px_60px_rgba(0,0,0,.08)]"><div className="mb-8 flex items-center justify-between"><span className="heading-font text-2xl">GibelaSA</span><span className="code-font text-[10px] uppercase tracking-widest">Journey preview</span></div><div className="route-line space-y-8"><div className="relative flex gap-4"><MapPin className="z-10 bg-[#f7f3ea]" size={26}/><div><p className="code-font text-xs text-black/45">START</p><p>Current location</p></div></div><div className="relative flex gap-4"><Footprints className="z-10 bg-[#f7f3ea]" size={26}/><div><p className="code-font text-xs text-black/45">4 MIN WALK</p><p>Randburg Taxi Rank</p></div></div><div className="relative flex gap-4"><BusFront className="z-10 bg-[#f7f3ea]" size={26}/><div><p className="code-font text-xs text-[#e9501b]">MINIBUS TAXI · R18</p><p>Randburg → Sandton</p></div></div><div className="relative flex gap-4"><MapPin className="z-10 bg-[#f7f3ea]" size={26}/><div><p className="code-font text-xs text-black/45">DESTINATION</p><p>Sandton</p></div></div></div></div></div>
<div className="flex flex-col justify-between p-7 sm:p-10 lg:p-14"><div><p className="section-kicker">01 · Flagship project · In development</p><h3 className="heading-font mt-5 text-5xl sm:text-6xl">GibelaSA</h3><p className="mt-6 max-w-xl text-lg leading-8 text-black/65">A journey-planning platform for South Africa&apos;s minibus taxi network. It combines taxi-rank and route data with walking segments, direct-route discovery and transfer planning.</p></div><div className="mt-10 space-y-7"><Tags items={["Flutter","NestJS","PostgreSQL","PostGIS","MapLibre"]}/><a href="https://github.com/MasieJr" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border-b border-black pb-1 text-sm">Follow the build <ArrowUpRight size={15}/></a></div></div></article>
<article className="mt-8 grid overflow-hidden border border-black/15 lg:grid-cols-[.85fr_1.15fr]"><div className="flex flex-col justify-between p-7 sm:p-10 lg:p-14"><div><p className="section-kicker">02 · Production system</p><h3 className="heading-font mt-5 text-5xl sm:text-6xl">Film Processing</h3><p className="mt-6 max-w-xl text-lg leading-8 text-black/65">I saw a paper-heavy workflow at work and built the solution myself. The system handles QR customer intake, store workflows, status tracking, notifications and multi-branch processing.</p></div><div className="mt-10 space-y-7"><Tags items={["Next.js","Prisma","PostgreSQL","Resend","Puppeteer"]}/><a href="https://film-process.masieseremu.co.za" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border-b border-black pb-1 text-sm">View live system <ArrowUpRight size={15}/></a></div></div><div className="relative min-h-[360px] border-t border-black/15 bg-black/5 lg:border-l lg:border-t-0"><Image src="/projects/fotofirst.webp" alt="Film processing system" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 55vw"/></div></article>
<article className="mt-8 grid gap-8 border border-black/15 p-7 sm:p-10 lg:grid-cols-[1fr_2fr] lg:p-14"><div><p className="section-kicker">03 · Earlier work</p><h3 className="heading-font mt-4 text-4xl">UniConnect</h3></div><div><p className="max-w-2xl text-lg leading-8 text-black/65">A university platform exploring the day-to-day student experience across web and mobile.</p><div className="mt-6"><Tags items={["React","Flutter","Node.js","MySQL"]}/></div></div></article>
</section>}